media: images
content:
  - name: hero
    label: Hero Section
    type: collection
    path: 'content'
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: rich-text